### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by kien-truong** [lyft/presto-gateway#108]
It's not obvious whether `presto-gateway` currently support SSL-enabled Presto or not. Because Presto-Gateway need to parse the query, it needs to terminate the client's SSL connection by itself before forwarding the request to a Presto coordinator. 

I suppose one cannot simply add an SSL backend and expects it to works.

**Comment by puneetjaiswal** [comment]
It should not be a problem if you are using signed certs on backend coordinator - https://github.com/lyft/presto-gateway/blob/master/proxyserver/src/main/java/com/lyft/data/proxyserver/ProxyServletImpl.java#L30
We are setting `TrustAll` in SSLFactory so it should work for self signed certs too.
Did you face any issue with this?

**Comment by kien-truong** [comment]
Thanks. We're just not sure how to setup presto-gateway with our certificate so that it accepts SSL connections from clients as well.

**Comment by puneetjaiswal** [comment]
1. If you are having a load-balancer before gateway, you could bind the certs on LB and let TLS terminate right there.
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-create-https-ssl-load-balancer.html

2. If you want GW to start with HTTPS you will have to add the certs here - 
https://github.com/lyft/presto-gateway/blob/master/gateway-ha/src/main/java/com/lyft/data/gateway/ha/config/RequestRouterConfiguration.java#L14

We recommend going with option 1 here.

**Comment by PennyAndWang** [comment]
> 1. If you are having a load-balancer before gateway, you could bind the certs on LB and let TLS terminate right there.
>    https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-create-https-ssl-load-balancer.html
> 2. If you want GW to start with HTTPS you will have to add the certs here -
>    https://github.com/lyft/presto-gateway/blob/master/gateway-ha/src/main/java/com/lyft/data/gateway/ha/config/RequestRouterConfiguration.java#L14
> 
> We recommend going with option 1 here.

@puneetjaiswal ， I want to try option 2, but  I am confused the difference  between  `requestRouter`  config  and  `applicationConnectors` config .

**Comment by johnwhumphreys** [comment]
@PennyAndWang - Did you manage to get option 2 working?  We are looking to do the same as we have end-to-end TLS requirements.

**Comment by labelhero** [comment]
@PennyAndWang or @johnwhumphreys Were you able to implement option 2 successfully. I am trying to implement option 2 however I am getting below error

````
io.dropwizard.configuration.ConfigurationValidationException: ../gateway-ha-config.yml has the following errors:
  * keyStorePassword should not be null or empty
  * keyStorePath should not be null

	at io.dropwizard.configuration.BaseConfigurationFactory.validate(BaseConfigurationFactory.java:238)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:128)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:89)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at com.lyft.data.gateway.ha.HaGatewayLauncher.main(HaGatewayLauncher.java:25)
````
@puneetjaiswal This is how I provided keystore details.By the way I am using self signed cert. Am I missing anything here?Please help
```
requestRouter:
  port: 8080
  name: prestoRouter
  historySize: 1000
  ssl: True
  keystorePath: <PATH/TO/keystore.jks>
  keystorePass: xxxxxxxx
  
  server:
  applicationConnectors:
    - type: https
      port: 8090
  adminConnectors:
    - type: http
      port: 8091
```

**Comment by johnwhumphreys** [comment]
My team got it working with SSL, but I wasn't paying attention to the details to be honest.  I'll see if I can get someone to drop some notes.

But first... the error says "keyStorePath" and you have "keystorePath" - any chance this is just a casing issue?  Same for the other word.

**Comment by labelhero** [comment]
@johnwhumphreys That's great!! Could you please drop some details whenever you have chance. Thanks..

**Comment by lanre3c** [comment]
Hi All, it's 2023 and I know I'm late to the party :) . I'm currently implementing this for my team. I'm using self get cert in local with my Mac hostname (example: 232929-123f) as the CN in the key&certificate. 

I'm getting 400 Invalid SNI error. I tried following recommendation here - 
https://stackoverflow.com/questions/69945173/org-eclipse-jetty-http-badmessageexception-400-invalid-sni but that doesn't seems to be helping. Can provide additional details if needed. I'll appreciate your suggestion/recommendation. Thanks 

ps
it works great connecting to http trino clusters. Just trying to get it to work with https trino endpoint has been a struggle. Thanks

**Comment by johnwhumphreys** [comment]
Just found this again.  For the next person, assuming it hasn't been fixed yet, we had made the following changes to get https working in the past.

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/6787442/225387355-f986d485-3807-4277-a289-5f0d36205f4c.png">

**Comment by lanre3c** [comment]
Hi,

Thanks so much for this - in all my research, I never even came close to
looking here.
If you don't mind me asking, would you know what other corresponding
changes were made in the gateway-ha-config.yml file to make these changes
above work.

I had to make the following changes after changing *HttpConnectorFactory*
to *HttpsConnectorFactory*
server:
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091

to

server:
  applicationConnectors:
   * - type: https*
      port: 8090
  adminConnectors:
    - type: http
      port: 8091

Just wanted to make sure I have that right.

 Thanks again!
