### ISSUE TITLE
Field 'query_id' doesn't have a default value

### ISSUE THREAD

**Issue by javens0601** [lyft/presto-gateway#187]

**Comment by javens0601** [comment]
ERROR [2022-10-25 02:26:01,831] com.lyft.data.gateway.ha.handler.QueryIdCachingProxyHandler: Error in proxying falling back to super call
! java.sql.SQLException: Field 'query_id' doesn't have a default value
! at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
! at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
! at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
! at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
! at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
! at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
! at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1340)
! at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
! at org.javalite.activejdbc.DB.execInsert(DB.java:683)
! ... 31 common frames omitted
! Causing: org.javalite.activejdbc.DBException: java.sql.SQLException: Field 'query_id' doesn't have a default value, query: INSERT INTO query_history (backend_url, created, query_text, source, user_name) VALUES (?, ?, ?, ?, ?),
