### ISSUE TITLE
proxying failure

### ISSUE THREAD

**Issue by kapurdheeraj** [lyft/presto-gateway#191]
We are hitting proxying failure issue for 2% of our requests. anybody observed this with presto-gateway deployment? This is completely random

```
DEBUG [2023-01-09 00:41:07,378] com.lyft.data.proxyserver.ProxyServletImpl.prestoRouter: 1209755980 proxying failed
! java.util.concurrent.TimeoutException: Idle timeout 30000 ms
! at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onIdleExpired(HttpConnectionOverHTTP.java:145)
! at org.eclipse.jetty.io.ssl.SslConnection.onIdleExpired(SslConnection.java:270)
! at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:401)
! at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)
! at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
! at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
! at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
! at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
! at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
! at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
! at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by rwilliams-r7** [comment]
@kapurdheeraj How did you resolve this bug? I currently have the same problem. Is this running in a k8s environment?
