### ISSUE TITLE
500: Request header too large

### ISSUE THREAD

**Issue by sawant-ankeeta** [lyft/presto-gateway#203]
Hi Team,

We have encountered an error in Presto Gateway and need assistance with modifying a property in the gateway configuration to increase the header size. Can you provide help on which property to modify for this purpose?

 DEBUG [2023-06-28 13:37:46,662] com.lyft.data.proxyserver.ProxyServletImpl.prestoRouter: 471459333 proxying content to upstream: 139 bytes
DEBUG [2023-06-28 13:37:46,666] com.lyft.data.proxyserver.ProxyServletImpl.prestoRouter: 471459333 proxying failed
! java.nio.BufferOverflowException: null
! at java.nio.Buffer.nextPutIndex(Buffer.java:525)
! at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:173)
! at org.eclipse.jetty.http.HttpGenerator.putSanitisedValue(HttpGenerator.java:947)
! at org.eclipse.jetty.http.HttpGenerator.putTo(HttpGenerator.java:963)
! at org.eclipse.jetty.http.HttpGenerator.generateHeaders(HttpGenerator.java:720)
! at org.eclipse.jetty.http.HttpGenerator.generateRequest(HttpGenerator.java:258)
! ... 53 common frames omitted
! Causing: org.eclipse.jetty.http.BadMessageException: 500: Request header too large

**Comment by lightshine001** [comment]
+1. I also see this issue. Do we have some place to set it?
